apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-discord
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: argocd-notifications-openbao
    kind: SecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Merge
  data:
    - secretKey: discord-webhook-url
      remoteRef:
        key: homelab/k8s-argocd/discord-webhook-url
        property: value
