apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-webhook-github
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: argocd-webhook-openbao
    kind: SecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: webhook.github.secret
      remoteRef:
        key: homelab/k8s-argocd/github-webhook-secret
        property: value
